In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

Numpy merupakan library python digunakan untuk komputasi matriks.
matplolib merupakan library python untuk presentasi data berupa grafik atau plot.

In [38]:
dataset = pd.read_csv('datapenduduk.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [39]:
print(x)

[[2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. PANGGANG' 'Islam']
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. KELAPA' 'Islam']
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. HARAPAN' 'Islam']
 ...
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'BAMBU APUS'
  'Aliran Kepercayaan']
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'LUBANG BUAYA'
  'Aliran Kepercayaan']
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'CEGER'
  'Aliran Kepercayaan']]


In [40]:
print(y)

[6.159e+03 6.405e+03 2.251e+03 ... 1.300e+01 3.000e+01 2.000e+00]


In [42]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='constant')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])   

In [43]:
print(x)

[[2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. PANGGANG' 'Islam']
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. KELAPA' 'Islam']
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. HARAPAN' 'Islam']
 ...
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'BAMBU APUS'
  'Aliran Kepercayaan']
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'LUBANG BUAYA'
  'Aliran Kepercayaan']
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'CEGER'
  'Aliran Kepercayaan']]


In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x)) 

In [45]:
 print(x)

[[1.0 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. PANGGANG' 'Islam']
 [1.0 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. KELAPA' 'Islam']
 [1.0 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. HARAPAN' 'Islam']
 ...
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'BAMBU APUS'
  'Aliran Kepercayaan']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'LUBANG BUAYA'
  'Aliran Kepercayaan']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'CEGER'
  'Aliran Kepercayaan']]


In [46]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)

In [47]:
print(y)

[719 725 530 ...  12  28   1]


In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [49]:
print(x_train)

[[1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIRACAS' 'SUSUKAN'
  'Katholik']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'TANAH ABANG'
  'BENDUNGAN HILIR' 'Islam']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'PASAR REBO' 'CIJANTUNG'
  'Aliran Kepercayaan']
 ...
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'SENEN' 'KRAMAT' 'Budha']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CAKUNG' 'JATINEGARA'
  'Islam']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'CILANGKAP'
  'Hindu']]


In [50]:
print(x_test)

[[1.0 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PASAR MINGGU' 'RAGUNAN'
  'Budha']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'MAKASAR' 'CIPINANG MELAYU'
  'Khonghuchu']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'DUREN SAWIT' 'PONDOK BAMBU'
  'Khonghuchu']
 ...
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'KELAPA GADING'
  'KELAPA GADING TIMUR' 'Khonghuchu']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'SENEN' 'KENARI' 'Hindu']
 [1.0 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'KEBAYORAN BARU'
  'PETOGOGAN' 'Hindu']]


In [51]:
print(y_train)

[ 328  841    4 ...  335 1016   39]


In [52]:
print(y_test)

[  78    4 1231  458   76  426  533  708   44   37  487  748  479  782
   10    0 1087  526   36 1201  131  854  998   22  625    0 1042  826
 1152 1243 1312  842   39   22 1049  929  469   66  965    1 1002  718
   49  244  481 1319  992  657  342    3  707    2   27 1212 1274   29
   75 1051   14  290 1357 1335  816  489  109 1351  174 1349  110  982
  285    1  857  616 1229  440 1296  413    7    0   43  797  627  988
  594 1209 1211  689    4  581   11  700 1107    5  656  228    0   61
  269 1074   19   12  248  340   16 1077   37   82   44  396 1245  429
  603  216  501  993   31 1233  572  214   64  470  704  831  451  588
   74 1187  303    0   11   23  729    0 1340   90 1153  229  364   12
  538  542  165 1185  784    5  862  492   41  620  529 1044  803 1103
 1110 1280 1317  561 1220  308   51  452   54  977  486   55    1  733
    3  283    1  455    0  121  278  811   53  757   60  638 1071    3
 1058  235  942  505  211  442  913 1178  179   22 1167  395  703   32
  799 